# AIRI event bridge: forward battle commentary events from the live player
# to a running AIRI desktop app, which speaks them through its character
# (the Prism commentator card). AIRI treats each event as an incoming chat
# message; the character reacts in its own voice and pulls facts through
# its pokemon_expert MCP tool on its own.
#
# Protocol (verified against AIRI 0.11.0's embedded @proj-airi/server-runtime):
#   endpoint  ws://127.0.0.1:6121/ws          (root path 404s every frame)
#   ->  {"type": "module:authenticate", "data": {"token": <authToken>}}
#   <-  {"json": {"type": "module:authenticated", "data": {"authenticated": true}}}
#       (server frames arrive superjson-wrapped; plain {type,data} is accepted
#        inbound — unwrap with msg.get("json", msg))
#   ->  {"type": "input:text", "data": {"text": ...}}   routed to the stage chat
#       (no module:announce — see the note in _handshake)
#
# The token lives in ~/.config/ai.moeru.airi/server-channel-config.json and
# is regenerated by the app, so it is always read fresh at connect time.
# There is no app-level heartbeat event: any frame refreshes peer health
# (ttl 60s), and the websockets library's automatic protocol pings cover
# quiet stretches.
#
# Manual test (AIRI must be running):
#   .venv/bin/python showdown/airi_bridge.py "Mic check from the bridge."
#
# Live commentary tap (for recording sessions — prints each battle beat and
# Prism's spoken reply as they happen; any authenticated peer receives the
# chat pushes):
#   .venv/bin/python showdown/airi_bridge.py --watch

from __future__ import annotations

import asyncio
import json
import sys

from pathlib import Path

import websockets

DEFAULT_URL = "ws://127.0.0.1:6121/ws"
CONFIG_PATH = Path.home() / ".config/ai.moeru.airi/server-channel-config.json"


def _load_token() -> str:
    try:
        return json.loads(CONFIG_PATH.read_text())["authToken"]
    except Exception as e:
        raise RuntimeError(
            f"couldn't read AIRI auth token from {CONFIG_PATH} ({e!r}); "
            "is the AIRI desktop app installed?") from e


def _unwrap(raw: str | bytes) -> dict:
    """Server frames are superjson envelopes: {"json": {...}, "meta": {...}}."""
    msg = json.loads(raw)
    return msg.get("json", msg) if isinstance(msg, dict) else {}


class AiriBridge:
    """Fire-and-forget text events to AIRI over its server WebSocket.

    send() is thread-safe and never blocks or raises: events are queued on
    the asyncio loop captured at start(), a background task owns the
    connection, and a dead/absent AIRI only costs a retry loop — the game
    must never stall or crash over commentary.
    """

    def __init__(self, url: str = DEFAULT_URL, name: str = "crystal-battle"):
        self._url = url
        self._name = name
        self._queue: asyncio.Queue[str] = asyncio.Queue(maxsize=32)
        self._loop: asyncio.AbstractEventLoop | None = None
        self._task: asyncio.Task | None = None
        self._connected = False
        self._was_connected: bool | None = None  # log state changes only

    async def start(self):
        self._loop = asyncio.get_running_loop()
        self._task = self._loop.create_task(self._run())
        self._task.add_done_callback(self._on_task_done)

    @staticmethod
    def _on_task_done(task):
        """The run task should only ever end via close()'s cancel; anything
        else is a bug we want LOUD, not a silently dead commentary feed."""
        if task.cancelled():
            return
        exc = task.exception()
        print(f"  airi-bridge: run task died unexpectedly: {exc!r}")

    def send(self, text: str):
        """Queue an event from any thread; drops oldest when backed up."""
        if self._loop is None or self._loop.is_closed():
            return
        self._loop.call_soon_threadsafe(self._enqueue, text)

    def _enqueue(self, text: str):
        while True:
            try:
                self._queue.put_nowait(text)
                return
            except asyncio.QueueFull:
                try:
                    self._queue.get_nowait()  # stale commentary: drop oldest
                except asyncio.QueueEmpty:
                    return

    async def close(self):
        if self._task is not None:
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
            self._task = None

    async def _run(self):
        backoff = 2.0
        pending: str | None = None  # event to (re)send; survives reconnects
        while True:
            try:
                async with websockets.connect(self._url) as ws:
                    await self._handshake(ws)
                    self._set_connected(True)
                    backoff = 2.0
                    drain = asyncio.get_running_loop().create_task(
                        self._drain(ws))
                    try:
                        while True:
                            if pending is None:
                                pending = await self._next_event(drain)
                            await ws.send(json.dumps({
                                "type": "input:text",
                                "data": {"text": pending},
                            }))
                            pending = None
                    finally:
                        drain.cancel()
            except asyncio.CancelledError:
                raise
            except BaseException as e:
                # BaseException on purpose: a silently swallowed task death
                # here means a dead commentary feed for the whole match
                self._set_connected(False, e)
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2, 60.0)

    async def _next_event(self, drain: asyncio.Task) -> str:
        """Wait for the next queued event, but also wake if the server
        closes the connection while we're idle (the drain task ends) —
        otherwise a dead socket goes unnoticed until the next beat."""
        getter = asyncio.ensure_future(self._queue.get())
        done, _ = await asyncio.wait({getter, drain},
                                     return_when=asyncio.FIRST_COMPLETED)
        if getter in done:
            return getter.result()
        getter.cancel()
        raise ConnectionError("server closed the connection while idle")

    async def _handshake(self, ws):
        await ws.send(json.dumps({
            "type": "module:authenticate",
            "data": {"token": _load_token()},
        }))
        async with asyncio.timeout(10):
            while True:
                msg = _unwrap(await ws.recv())
                if msg.get("type") == "module:authenticated":
                    if not msg.get("data", {}).get("authenticated"):
                        raise RuntimeError("AIRI rejected the auth token")
                    break
        # No module:announce: a plain authenticated peer already gets
        # input:text ingested (soak-verified: chat events pushed back,
        # generations fired) and announcing with possibleEvents=[] buys
        # nothing. NOTE the server drops peers with no app-level frame for
        # 60s (websockets protocol pings do NOT refresh its heartbeat) —
        # quiet stretches between beats/games rely on the reconnect loop.

    async def _drain(self, ws):
        """Consume inbound frames (registry syncs etc.) so the connection's
        read queue never applies backpressure."""
        async for _ in ws:
            pass

    def _set_connected(self, up: bool, err: Exception | None = None):
        self._connected = up
        if up != self._was_connected:
            self._was_connected = up
            if up:
                print(f"  airi-bridge: connected to {self._url}")
            else:
                print(f"  airi-bridge: not connected ({err!r}); "
                      "retrying in the background")


async def watch(url: str = DEFAULT_URL):
    """Commentary tap: print each battle beat and the character's reply.

    Read-only peers send no app frames, and the server drops anything
    silent for 60s — so we re-send authenticate every 30s as a keepalive
    and reconnect on any drop. output:gen-ai:chat:complete carries both
    the triggering input (data.text) and the reply (data.message.content);
    the :message variant is skipped to avoid duplicates.
    """
    import time
    while True:
        try:
            async with websockets.connect(url) as ws:
                await ws.send(json.dumps({
                    "type": "module:authenticate",
                    "data": {"token": _load_token()},
                }))
                print("-- tap connected, waiting for commentary --",
                      flush=True)
                last_keepalive = time.monotonic()
                while True:
                    try:
                        raw = await asyncio.wait_for(ws.recv(), timeout=5)
                    except asyncio.TimeoutError:
                        raw = None
                    if time.monotonic() - last_keepalive > 30:
                        await ws.send(json.dumps({
                            "type": "module:authenticate",
                            "data": {"token": _load_token()},
                        }))
                        last_keepalive = time.monotonic()
                    if raw is None:
                        continue
                    msg = _unwrap(raw)
                    if msg.get("type") != "output:gen-ai:chat:complete":
                        continue
                    data = msg.get("data", {})
                    beat = (data.get("text") or "").strip()
                    message = data.get("message") or {}
                    cat = message.get("categorization") or {}
                    # prefer AIRI's extracted 'speech' (drops reasoning) so
                    # this view matches what the relay speaks into the room
                    reply = (cat.get("speech")
                             or message.get("content") or "").strip()
                    stamp = time.strftime("%H:%M:%S")
                    if beat:
                        print(f"\n[{stamp}] {beat}", flush=True)
                    if reply:
                        print(f"    Prism: {reply}", flush=True)
        except (KeyboardInterrupt, asyncio.CancelledError):
            raise
        except Exception as e:
            print(f"-- tap disconnected ({e!r}); retrying in 3s --",
                  flush=True)
            await asyncio.sleep(3)


async def _main():
    if "--watch" in sys.argv:
        await watch()
        return
    text = sys.argv[1] if len(sys.argv) > 1 else "Mic check from the bridge."
    bridge = AiriBridge()
    await bridge.start()
    bridge.send(text)
    # give the run task time to connect and flush the one event
    for _ in range(50):
        await asyncio.sleep(0.2)
        if bridge._connected and bridge._queue.empty():
            break
    await asyncio.sleep(0.5)  # let the frame actually go out
    await bridge.close()
    print("sent" if bridge._queue.empty() else "NOT sent (AIRI unreachable?)")


if __name__ == "__main__":
    try:
        asyncio.run(_main())
    except KeyboardInterrupt:
        pass
